# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_auto_20180718_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changebalance',
            options={'verbose_name': 'Изменение', 'verbose_name_plural': 'Изменения'},
        ),
        migrations.AddField(
            model_name='changebalance',
            name='change',
            field=models.CharField(choices=[('Расход', 'Расход'), ('Поступление', 'Поступление')], default='Расход', max_length=12),
        ),
        migrations.AddField(
            model_name='changebalance',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма:'),
        ),
        migrations.AlterField(
            model_name='changebalance',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name='Категория:'),
        ),
        migrations.AlterField(
            model_name='changebalance',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название:'),
        ),
    ]
