# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_auto_20180718_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='changebalance',
            name='period',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='planning.Period', verbose_name='Период'),
        ),
    ]
