# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_changebalance_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changebalance',
            name='period',
        ),
    ]
