# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_auto_20180719_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ('-id', 'name'), 'verbose_name': 'Период', 'verbose_name_plural': 'Периоды'},
        ),
        migrations.AddField(
            model_name='changebalance',
            name='period',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='planning.Period', verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='changebalance',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Дата:'),
        ),
        migrations.AlterField(
            model_name='changebalance',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма:'),
        ),
        migrations.AlterField(
            model_name='period',
            name='end_day',
            field=models.DateField(default=datetime.date(2018, 8, 21), verbose_name='Конец периода'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_day',
            field=models.DateField(default=datetime.date.today, verbose_name='Начало периода'),
        ),
    ]
