# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_auto_20180721_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changebalance',
            options={'ordering': ['-id'], 'verbose_name': 'Изменение', 'verbose_name_plural': 'Изменения'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['-id'], 'verbose_name': 'Период', 'verbose_name_plural': 'Периоды'},
        ),
        migrations.AlterField(
            model_name='period',
            name='end_day',
            field=models.DateField(default=datetime.date(2018, 8, 23), verbose_name='Конец периода'),
        ),
    ]
